RabbitMQ/Controllers/RabbitMQController.cs
using System.Security.Authentication;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using RabbitMQ.Client;
using System.Net.Security;
using Microsoft.AspNetCore.Hosting;
using System;
using SuperRocket.Message;
using Newtonsoft.Json;
using Microsoft.Extensions.Configuration;

namespace RabbitMQ.Controllers
{
    public class RabbitMQController : Controller
    {
        ConnectionFactory _rabbitConnection;
        IHostingEnvironment _env;
        public IConfiguration Configuration { get; set; }

        public RabbitMQController([FromServices] ConnectionFactory rabbitConnection, IHostingEnvironment env, IConfiguration configuration)
        {
            _env = env;
            Configuration = configuration;
            if (_env.IsDevelopment())
            {
                var hostName = Configuration["RabbitMQ:HostName"].ToString();
                var userName = Configuration["RabbitMQ:UserName"].ToString();
                var password = Configuration["RabbitMQ:Password"].ToString();
                _rabbitConnection = new ConnectionFactory { HostName = hostName, UserName = userName, Password = password };
            }
            else
            {
                _rabbitConnection = rabbitConnection;
            }
            
            SslOption opt = _rabbitConnection.Ssl;
            if (opt != null && opt.Enabled)
            {
                opt.Version = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;

                // Only needed if want to disable certificate validations
                opt.AcceptablePolicyErrors = SslPolicyErrors.RemoteCertificateChainErrors |
                    SslPolicyErrors.RemoteCertificateNameMismatch | SslPolicyErrors.RemoteCertificateNotAvailable;
            }
        }

    
        public IActionResult Receive()
        {
            try
            {
                using (var connection = _rabbitConnection.CreateConnection())
                using (var channel = connection.CreateModel())
                {
                    CreateQueue(channel);
                    var data = channel.BasicGet("rabbit-test", true);
                    if (data != null)
                    {
                        ViewData["message"] = Encoding.UTF8.GetString(data.Body);
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("RabbitMQController-Receive:" + ex.Message);
            }
            
            return View();
        }

        public IActionResult Send(string message)
        {

            if (message != null && message != "") {
                try
                {
                    using (var connection = _rabbitConnection.CreateConnection())
                    using (var channel = connection.CreateModel())
                    {
                        CreateQueue(channel);
                        var body = Encoding.UTF8.GetBytes(message);
                        channel.BasicPublish(exchange: "",
                                             routingKey: "rabbit-test",
                                             basicProperties: null,
                                             body: body);
                    }
                }
                catch (System.Exception ex)
                {
                    Console.WriteLine("RabbitMQController-Send:" + ex.Message);
                }
            }
            return View();
        }


        public IActionResult PublishMessageToRabbitMQ([FromBody] ExcelFileMessage message)
        {
            if (message != null)
            {
                try
                {
                    using (var connection = _rabbitConnection.CreateConnection())
                    using (var channel = connection.CreateModel())
                    {
                        CreateSuperRocketQueue(channel);
                        var body = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(message));
                        ViewData["message"] = Encoding.UTF8.GetString(body);
                        channel.BasicPublish(exchange: "superrocket.exchange",
                                             routingKey: "superrocket.queue.excelfilemessage",
                                             basicProperties: null,
                                             body: body);
                    }
                }
                catch (System.Exception ex)
                {
                    Console.WriteLine("RabbitMQController-PublishMessageToRabbitMQ:" + ex.Message);
                }
            }
            return View();
        }
        protected void CreateSuperRocketQueue(IModel channel)
        {
            try
            {
                channel.QueueDeclare(queue: "superrocket.queue.excelfilemessage",
                                     durable: false,
                                     exclusive: false,
                                     autoDelete: false,
                                     arguments: null);
            }
            catch (System.Exception ex)
            {
                Console.WriteLine("RabbitMQController-CreateQueue:" + ex.Message);
            }
        }
        protected void CreateQueue(IModel channel)
        {
            try
            {
                channel.QueueDeclare(queue: "rabbit-test",
                                     durable: false,
                                     exclusive: false,
                                     autoDelete: false,
                                     arguments: null);
            }
            catch (System.Exception ex)
            {
                Console.WriteLine("RabbitMQController-CreateQueue:" + ex.Message);
            }
        }
    }
}

RabbitMQ/Views/RabbitMQ/PublishMessageToRabbitMQ.cshtml
@{
    ViewData["Title"] = "Receive Data";
}
<h2>@ViewData["Title"].</h2>
<h3>Message=@ViewData["Message"]</h3>
<h3>Message=@ViewData["EasyMessage"]</h3>

RabbitMQ/Views/RabbitMQ/Receive.cshtml
@{
    ViewData["Title"] = "Receive Data";
}
<h2>@ViewData["Title"].</h2>
<h3>Message=@ViewData["Message"]</h3>
<h3>Message=@ViewData["EasyMessage"]</h3>

RabbitMQ/Views/RabbitMQ/Send.cshtml
@{
    ViewData["Title"] = "Send Data";
}
<h2>@ViewData["Title"].</h2>

<form asp-controller="RabbitMQ"
      asp-action="Send"
      method="post">
    Message:
    <input type="text" name="Message" value="" />
    <br />
    <input type="submit" value="Send" />
</form>

RabbitMQ/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RabbitMQ</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                  <a asp-area="" asp-controller="RabbitMQ" asp-action="Receive" class="navbar-brand">RabbitMQ</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="RabbitMQ" asp-action="Receive">Receive</a></li>
                    <li><a asp-area="" asp-controller="RabbitMQ" asp-action="Send">Send</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - RabbitMQ</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>